import type { AuthLocalization } from "@neondatabase/auth-ui";

/**
 * Tradução PT-BR das telas prontas do Neon Auth (@neondatabase/auth-ui). Cobre login/cadastro
 * e gestão de organização (nosso "workspace") e membros — as chaves não listadas aqui caem no
 * padrão em inglês da biblioteca.
 */
export const ptBR: AuthLocalization = {
  SIGN_IN: "Entrar",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_DESCRIPTION: "Informe seu e-mail e senha para entrar.",
  SIGN_UP: "Criar conta",
  SIGN_UP_ACTION: "Criar conta",
  SIGN_UP_DESCRIPTION: "Crie sua conta para começar a usar o painel.",
  SIGN_OUT: "Sair",
  EMAIL: "E-mail",
  EMAIL_PLACEHOLDER: "voce@empresa.com",
  EMAIL_REQUIRED: "Informe o e-mail",
  PASSWORD: "Senha",
  PASSWORD_PLACEHOLDER: "Sua senha",
  PASSWORD_REQUIRED: "Informe a senha",
  PASSWORD_TOO_SHORT: "Senha muito curta",
  PASSWORD_TOO_LONG: "Senha muito longa",
  PASSWORDS_DO_NOT_MATCH: "As senhas não coincidem",
  CONFIRM_PASSWORD: "Confirmar senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Repita a senha",
  CONFIRM_PASSWORD_REQUIRED: "Confirme a senha",
  NAME: "Nome",
  NAME_PLACEHOLDER: "Seu nome",
  FORGOT_PASSWORD: "Esqueci minha senha",
  FORGOT_PASSWORD_ACTION: "Enviar link de redefinição",
  FORGOT_PASSWORD_DESCRIPTION: "Informe seu e-mail para receber um link de redefinição de senha.",
  FORGOT_PASSWORD_LINK: "Esqueceu a senha?",
  RESET_PASSWORD: "Redefinir senha",
  RESET_PASSWORD_ACTION: "Redefinir senha",
  RESET_PASSWORD_DESCRIPTION: "Escolha uma nova senha.",
  RESET_PASSWORD_SUCCESS: "Senha redefinida com sucesso.",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  DONT_HAVE_AN_ACCOUNT: "Ainda não tem conta?",
  GO_BACK: "Voltar",
  CANCEL: "Cancelar",
  SAVE: "Salvar",
  UPDATE: "Atualizar",
  DELETE: "Excluir",
  REMOVE: "Remover",
  CONTINUE: "Continuar",
  UPDATED_SUCCESSFULLY: "Atualizado com sucesso.",

  ORGANIZATION: "Workspace",
  ORGANIZATIONS: "Workspaces",
  ORGANIZATIONS_DESCRIPTION: "Alterne entre os workspaces dos quais você faz parte.",
  ORGANIZATION_NAME: "Nome do workspace",
  ORGANIZATION_NAME_PLACEHOLDER: "Ex.: Cliente Acme",
  ORGANIZATION_NAME_DESCRIPTION: "O nome exibido para o seu workspace.",
  ORGANIZATION_SLUG: "Identificador (URL)",
  ORGANIZATION_SLUG_PLACEHOLDER: "cliente-acme",
  ORGANIZATION_SLUG_DESCRIPTION: "Usado na URL do workspace.",
  ORGANIZATION_ALREADY_EXISTS: "Já existe um workspace com esse identificador.",
  ORGANIZATION_NOT_FOUND: "Workspace não encontrado.",
  CREATE_ORGANIZATION: "Novo workspace",
  CREATE_ORGANIZATION_SUCCESS: "Workspace criado com sucesso.",
  DELETE_ORGANIZATION: "Excluir workspace",
  DELETE_ORGANIZATION_DESCRIPTION:
    "Remove permanentemente o workspace e todos os seus dados (contatos, campanhas, templates). Essa ação não pode ser desfeita.",
  DELETE_ORGANIZATION_SUCCESS: "Workspace excluído.",
  LEAVE_ORGANIZATION: "Sair do workspace",
  LEAVE_ORGANIZATION_CONFIRM: "Tem certeza que deseja sair deste workspace?",
  LEAVE_ORGANIZATION_SUCCESS: "Você saiu do workspace.",
  NO_ACTIVE_ORGANIZATION: "Nenhum workspace selecionado",

  MEMBER: "Membro",
  MEMBERS: "Membros",
  MEMBERS_DESCRIPTION: "Pessoas com acesso a este workspace.",
  MEMBER_NOT_FOUND: "Membro não encontrado.",
  ROLE: "Papel",
  OWNER: "Proprietário",
  ADMIN: "Administrador",
  UPDATE_ROLE: "Alterar papel",
  UPDATE_ROLE_DESCRIPTION: "Altere o papel deste membro no workspace.",
  MEMBER_ROLE_UPDATED: "Papel atualizado.",
  REMOVE_MEMBER: "Remover membro",
  REMOVE_MEMBER_CONFIRM: "Tem certeza que deseja remover este membro do workspace?",
  REMOVE_MEMBER_SUCCESS: "Membro removido.",

  INVITE_MEMBER: "Convidar",
  INVITE_MEMBER_DESCRIPTION: "Convide alguém para este workspace por e-mail.",
  PENDING_INVITATIONS: "Convites pendentes",
  PENDING_INVITATIONS_DESCRIPTION: "Convites enviados que ainda não foram aceitos.",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Convites de workspace que você recebeu.",
  ACCEPT_INVITATION: "Aceitar convite",
  ACCEPT_INVITATION_DESCRIPTION: "Você foi convidado para participar de um workspace.",
  INVITATION_ACCEPTED: "Convite aceito.",
  INVITATION_REJECTED: "Convite recusado.",
  INVITATION_CANCELLED: "Convite cancelado.",
  INVITATION_EXPIRED: "Este convite expirou.",
  INVITATION_NOT_FOUND: "Convite não encontrado.",
  CANCEL_INVITATION: "Cancelar convite",
  ACCEPT: "Aceitar",
  REJECT: "Recusar",
} as AuthLocalization;
